os:
- linux
dist: bionic
language: python

services:
- docker

if: (type == push) OR (type == pull_request AND fork == true)  # do not build anything for PRs

stages: 
- name: test

jobs:
  include:
  - stage: test
    name: Run build, style, unit and integration tests
    script:
    # docker build image
    - docker build -t zavolab/htsinfer .
    # docker run image
    - docker run zavolab/htsinfer
    # style tests
    - flake8 
    - pylint --rcfile pylint.cfg setup.py
    - pylint --rcfile pylint.cfg src/
    # unit tests
    - python -m pytest
    - coverage run --source src -m pytest
    - coveralls
    # integration tests
    - src/htsinfer.py --help
    - src/htsinfer.py --debug

    # push image to Docker Hub
    # docker login
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - echo Pushing Docker Image
    - # Version : 
    - docker tag ${DOCKER_REPO}:latest ${DOCKER_REPO}:${Version}
    - docker push ${DOCKER_ORGANIZATiON}/${DOCKER_REPO}:${Version}
     


