os:
- linux
dist: bionic
language: python

services:
- docker

if: (type == push) OR (type == pull_request AND fork == true)  # do not build anything for PRs

env:
  global:
  - VERSION: <Version> 

stages: 
- name: test

jobs:
  include:
  - stage: test
    name: Run build, style, unit and integration tests
    script:
    # docker build image
    - docker build -t zavolab/htsinfer .
    # docker run image
    - docker run zavolab/htsinfer
    # style tests
    - flake8 
    - pylint --rcfile pylint.cfg setup.py
    - pylint --rcfile pylint.cfg src/
    # unit tests
    - python -m pytest
    - coverage run --source src -m pytest
    - coveralls
    # integration tests
    - src/htsinfer.py --help
    - src/htsinfer.py --debug

deploy:
  # Publishing on TestPyPI
- provider: pypi
  user: "rohank63"
  password: ${PTEST_TOKEN}  
  skip_existing: true
  distributions: "sdist bdist_wheel"
  server: https://test.pypi.org/
  on:
    tags: true 
    repo: zavolanlab/htsinfer  
  # Publishing on PyPI  
- provider: pypi
  user: "rohank63"
  password: ${PYPI_TOKEN} 
  skip_existing: true 
  distributions: "sdist bdist_wheel"
  on:
    tags: true  
    repo: zavolanlab/htsinfer 

    
after sucess:
  # docker build image
- docker build -t zavolab/htsinfer .
  # docker run image
- docker run zavolab/htsinfer
- docker tag ${DOCKER_REPO}:latest
- docker tag ${DOCKER_REPO}:${VERSION}
  # push image to Docker Hub
  # docker login
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
- echo Pushing Docker Image
- docker push ${DOCKER_ORGANIZATiON}/${DOCKER_REPO}:${VERSION}

     


