os:
- linux
dist: bionic
language: python

services:
- docker

if: (type == push) OR (type == pull_request AND fork == true)  # do not build anything for PRs

env:
  global:
  - VERSION: <Version> 

stages: 
- name: test

jobs:
  include:
  - stage: test
    name: Run build, style, unit and integration tests
    script:
    # docker build image
    - docker build -t zavolab/htsinfer .
    # docker run image
    - docker run zavolab/htsinfer
    # style tests
    - flake8 
    - pylint --rcfile pylint.cfg setup.py
    - pylint --rcfile pylint.cfg src/
    # unit tests
    - python -m pytest
    - coverage run --source src -m pytest
    - coveralls
    # integration tests
    - src/htsinfer.py --help
    - src/htsinfer.py --debug

deploy:
  # Publishing on TestPyPI
- provider: pypi
  user: "rohank63"
  password: ${PTEST_TOKEN}  
  skip_existing: true
  distributions: "sdist bdist_wheel"
  server: https://test.pypi.org/
  on:
    tags: true 
    repo: zavolanlab/htsinfer  
  # Publishing on PyPI  
- provider: pypi
  user: "rohank63"
  password: ${PYPI_TOKEN} 
  skip_existing: true 
  distributions: "sdist bdist_wheel"
  on:
    tags: true  
    repo: zavolanlab/htsinfer 

after_success:
- export REPO=${DOCKER_ORGANIZATION}/${DOCKER_REPO} 
  # docker build image
- docker build -t ${REPO} .
  # docker run image
- docker run ${REPO}
- docker tag ${REPO} ${REPO}:${VERSION}
- docker tag ${REPO} ${REPO}:latest
  # push image to Docker Hub
  # docker login
- echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USER} --password-stdin
- echo PUSHING DOCKER IMAGE
- docker push ${REPO}

     


